" BASE

set enc=utf-8
set fileencoding=utf-8
set nocompatible                 " Don't try to be vi compatible

filetype off                     " Helps force plugins to load correctly when it is turned back on below

syntax enable
syntax on

set smartindent
set ruler                         " Show the line and column numbers of the cursor.
set wrap
set textwidth=0                   " Hard-wrap long lines as you type them.
set formatoptions=tcqrn1
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab                     " Insert spaces when TAB is pressed.
set noshiftround
set hidden                        " Allow hidden buffers
set ttyfast                       " rendering opt
set laststatus=2                  " status bar
set showmode                      " Show current mode.
set showcmd
set noerrorbells                  " Please no more beep
set modeline                      " Enable mode line
set magic                         " Use 'magic' patterns (extended regular expressions).
set smartindent                   " well smart indent :)
set termguicolors
set foldmethod=indent
set foldlevel=99
set number relativenumber
set clipboard=unnamed
set hlsearch
set incsearch


augroup numbertoggle
  autocmd!
  autocmd BufEnter,FocusGained,InsertLeave * set relativenumber
  autocmd BufLeave,FocusLost,InsertEnter   * set norelativenumber
augroup END

" Leader Mapping

let mapleader = ","
let maplocalleader=";"

" PLUGINS

call plug#begin('~/.vim/plugged')


" Core Plugins "
Plug 'ycm-core/YouCompleteMe'         " Autocomplete "
Plug 'dense-analysis/ale'             " Linter "

Plug 'mileszs/ack.vim'

Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'

Plug 'tpope/vim-repeat'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-abolish'
Plug 'tpope/vim-fugitive'                                               " Git wrapper
Plug 'tpope/vim-eunuch'
Plug 'tpope/vim-endwise'

Plug 'yuttie/comfortable-motion.vim'

Plug 'easymotion/vim-easymotion'                                        " Navigation

Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }                 " On-demand loading
Plug 'tiagofumo/vim-nerdtree-syntax-highlight'

Plug 'ervandew/supertab'
Plug 'andymass/vim-matchup'
Plug 'tmhedberg/SimpylFold'                                             " zc: close fold , zo: open
Plug 'zhou13/vim-easyescape'
Plug 'kshenoy/vim-signature'
Plug 'haya14busa/incsearch.vim'
Plug 'qpkorr/vim-bufkill'

" Theme "

Plug 'flazz/vim-colorschemes'                                           " Themes
Plug 'bling/vim-bufferline'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

Plug 'kien/rainbow_parentheses.vim'                                     " parenthesis color
Plug 'mhinz/vim-startify'
Plug 'ryanoasis/vim-devicons'

Plug 'rakr/vim-one'
Plug 'sonph/onehalf', {'rtp': 'vim/'}
Plug 'morhetz/gruvbox'

" ----------------------------

Plug 'ntpeters/vim-better-whitespace'

" C "


" Python "

Plug 'davidhalter/jedi-vim'
Plug 'heavenshell/vim-pydocstring'                                      " Generate Docstring :Pydocstring
Plug 'jeetsukumaran/vim-pythonsense'
Plug 'plytophogy/vim-virtualenv'

" Lua "

Plug 'tbastos/vim-lua'

" Latex

Plug 'lervag/vimtex'
Plug 'matze/vim-tex-fold'

" Snippets

Plug  'SirVer/ultisnips'
Plug 'honza/vim-snippets'

" Markdown

Plug 'plasticboy/vim-markdown'
Plug 'suan/vim-instant-markdown'

" Tag

Plug 'majutsushi/tagbar'
Plug 'vim-scripts/taglist.vim'

" Add Text objects "

Plug 'wellle/targets.vim'

" Writting

Plug 'davidbeckingsale/writegood.vim'   " :Write{goodEnable/Disable/Toggle}
Plug 'reedes/vim-wordy'
Plug 'Ron89/thesaurus_query.vim'        " :Thesaurus your phrase "
Plug 'junegunn/limelight.vim'           " :Limelight [0.0 ~ 1.0], Limelight!

" MISC

Plug 'dhruvasagar/vim-zoom'
Plug 'rhlobo/vim-super-retab'                                           " Space2Tab, Tab2Space, RetabIndent

" Todo the following plugins I should be able to understand those :)

Plug 'junegunn/goyo.vim'        " ::Goyo{!}
Plug 'romainl/vim-cool'
Plug 'nathanaelkane/vim-indent-guides'
Plug 'townk/vim-autoclose'
Plug 'ludovicchabant/vim-gutentags'
call plug#end()

filetype plugin indent on        " For plugins to load correctly

let g:UltiSnipsEditSplit="vertical"

" Python path

let g:python2_host_prog = '/usr/bin/python'
let g:python3_host_prog = '/usr/bin/python3'
let g:python_highlight_all = 1

set tags=./tags,tags;$HOME

" Python

nnoremap <leader>is :<c-u>ImpSort!<cr>

" YCM

let g:ycm_key_list_select_completion = ['<C-n>', '<Down>']
let g:ycm_key_list_previous_completion = ['<C-p>', '<Up>']
let g:SuperTabDefaultCompletionType = '<C-n>'

" Snippets

let g:UltiSnipsExpandTrigger = '<tab>'
let g:UltiSnipsJumpForwardTrigger = '<tab>'
let g:UltiSnipsJumpBackwardTrigger = '<s-tab>'
let g:UltiSnipsSnippetDirectories = [
            \ "/home/nizam/snippets/Ultisnips",
            \ "UltiSnips"
            \ ]

"set rtp+=~/snippets

" Language spelling

let g:is_pythonsense_suppress_motion_keymaps = 1

" https://stackoverflow.com/questions/13621845/vim-pumvisible-call-putting-in-random-text
let g:AutoClosePreserveDotReg = 0

set laststatus=2
set ts=2 sw=2 sts=2 et
set backspace=indent,eol,start


setlocal spell spelllang=en_us

source ~/dotfile/vim/fzf.vim
source ~/dotfile/vim/pythonrc.vim
source ~/dotfile/vim/theme.vim
source ~/dotfile/vim/mapping.vim

" Hack

if $TERM == "screen-256color"
  let &t_ut=''
  set termguicolors
            let &t_8f = "\e[38;2;%lu;%lu;%lum"
            let &t_8b = "\e[48;2;%lu;%lu;%lum"
    hi Normal guifg=NONE guibg=NONE ctermfg=NONE ctermbg=NONE
    let &t_ti = &t_ti . "\033]10;#f6f3e8\007\033]11;#242424\007"
    let &t_te = &t_te . "\033]110\007\033]111\007"
endif

set pastetoggle=<F4>
let b:ale_linters = ['flake8']
