" BASE

set enc=utf-8
set fileencoding=utf-8
set nocompatible                 " Don't try to be vi compatible

filetype off                     " Helps force plugins to load correctly when it is turned back on below

syntax enable
syntax on

set smartindent
set ruler                         " Show the line and column numbers of the cursor.
set wrap
set textwidth=0                   " Hard-wrap long lines as you type them.
set formatoptions=tcqrn1
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab                     " Insert spaces when TAB is pressed.
set noshiftround
set hidden                        " Allow hidden buffers
set ttyfast                       " rendering opt
set laststatus=2                  " status bar
set showmode                      " Show current mode.
set showcmd
set noerrorbells                  " Please no more beep
set modeline                      " Enable mode line
set magic                         " Use 'magic' patterns (extended regular expressions).
set smartindent                   " well smart indent :)
set termguicolors
set foldmethod=indent
set foldlevel=99
set number relativenumber
set clipboard=unnamed
set hlsearch
set incsearch

augroup numbertoggle
  autocmd!
  autocmd BufEnter,FocusGained,InsertLeave * set relativenumber
  autocmd BufLeave,FocusLost,InsertEnter   * set norelativenumber
augroup END

" Leader Mapping

let mapleader = ","
let maplocalleader=";"

" ============
" Core Plugins
" ------------

call plug#begin('~/.vim/plugged')

Plug 'ycm-core/YouCompleteMe'         " Autocomplete "
Plug 'dense-analysis/ale'             " Linter "

Plug 'mileszs/ack.vim'

Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'

Plug 'tpope/vim-repeat'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-abolish'
Plug 'tpope/vim-fugitive'                                               " Git wrapper
Plug 'tpope/vim-eunuch'
Plug 'tpope/vim-endwise'

Plug 'yuttie/comfortable-motion.vim'

Plug 'easymotion/vim-easymotion'                                        " Navigation

Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }                 " On-demand loading
Plug 'tiagofumo/vim-nerdtree-syntax-highlight'

Plug 'ervandew/supertab'
Plug 'andymass/vim-matchup'
Plug 'tmhedberg/SimpylFold'                                             " zc: close fold , zo: open
Plug 'zhou13/vim-easyescape'
Plug 'kshenoy/vim-signature'
Plug 'haya14busa/incsearch.vim'
Plug 'qpkorr/vim-bufkill'
"nnoremap <silent> <c-left> :CmdResizeLeft<cr> idem with up right ...
Plug 'breuckelen/vim-resize'

" Theme "

Plug 'flazz/vim-colorschemes'                                           " Themes
"Plug 'bling/vim-bufferline'

Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

Plug 'kien/rainbow_parentheses.vim'                                     " parenthesis color
Plug 'mhinz/vim-startify'
Plug 'ryanoasis/vim-devicons'

Plug 'romainl/flattened'

Plug 'arcticicestudio/nord-vim'
Plug 'rakr/vim-one'
Plug 'kaicataldo/material.vim'
Plug 'sonph/onehalf', {'rtp': 'vim/'}
Plug 'morhetz/gruvbox'
Plug 'rakr/vim-two-firewatch'
Plug 'ntpeters/vim-better-whitespace'

" C "


" Python "

Plug 'davidhalter/jedi-vim'
Plug 'heavenshell/vim-pydocstring'                                      " Generate Docstring :Pydocstring
Plug 'jeetsukumaran/vim-pythonsense'
Plug 'plytophogy/vim-virtualenv'

" Lua "

Plug 'tbastos/vim-lua'

" Latex

Plug 'lervag/vimtex'
Plug 'matze/vim-tex-fold'

" Snippets

Plug  'SirVer/ultisnips'
Plug 'honza/vim-snippets'

" Markdown

Plug 'plasticboy/vim-markdown'
Plug 'suan/vim-instant-markdown'

" Tag

Plug 'majutsushi/tagbar'
Plug 'vim-scripts/taglist.vim'

" Add Text objects "

Plug 'wellle/targets.vim'

" Writting

Plug 'davidbeckingsale/writegood.vim'   " :Write{goodEnable/Disable/Toggle}
Plug 'reedes/vim-wordy'
Plug 'Ron89/thesaurus_query.vim'        " :Thesaurus your phrase "
Plug 'junegunn/limelight.vim'           " :Limelight [0.0 ~ 1.0], Limelight!

" MISC

Plug 'dhruvasagar/vim-zoom'
Plug 'rhlobo/vim-super-retab'                                           " Space2Tab, Tab2Space, RetabIndent

" Todo the following plugins I should be able to understand those :)

Plug 'junegunn/goyo.vim'        " ::Goyo{!}
"Plug 'romainl/vim-cool'
"Plug 'nathanaelkane/vim-indent-guides'
Plug 'townk/vim-autoclose'
Plug 'ludovicchabant/vim-gutentags'
call plug#end()

filetype plugin indent on        " For plugins to load correctly

" Tags

set tags=./tags,tags;$HOME

" Autocompletion: YCM

let g:ycm_key_list_select_completion = ['<C-n>', '<Down>']
let g:ycm_key_list_previous_completion = ['<C-p>', '<Up>']
let g:SuperTabDefaultCompletionType = '<C-n>'

" Linter: ALE

let g:ale_fix_on_save = 1
let g:ale_sign_error = '😡'
let g:ale_sign_warning = '😭'
let g:ale_linters_explicit = 1
let g:ale_lint_on_text_changed = 'never'
let g:ale_lint_on_enter = 0
let g:ale_set_highlights = 0

let g:airline#extensions#ale#enabled = 1

nnoremap <space>l :lnext<CR>
nnoremap <space>p :lprevious<CR>
nnoremap <space>r :lrewind<CR>

let b:ale_linters = ['flake8']

set omnifunc=ale#completion#OmniFunc

" https://stackoverflow.com/questions/13621845/vim-pumvisible-call-putting-in-random-text
let g:AutoClosePreserveDotReg = 0

set laststatus=2
set ts=2 sw=2 sts=2 et
set backspace=indent,eol,start

setlocal spell spelllang=en_us
"set nospell

source ~/dotfile/vim/fzf.vim
source ~/dotfile/vim/pythonrc.vim
source ~/dotfile/vim/snippets/snippets.vim
source ~/dotfile/vim/themes/theme_nord.vim
source ~/dotfile/vim/mapping.vim

" Hack

set pastetoggle=<F4>

